Dashboard Sprint 11de
KnowageLabs/Knowage-Server-Frontend pull request #28
Opened 2023-06-19 12:58 UTC by dbulatovicx32

https://knowage-devops.knowage-suite.eu/vuepress/dashboard/sprints.html#sprint-11-june-2023

2023-06-26 12:08 UTC, Redjaw requested changes

2023-06-26 14:16 UTC, dbulatovicx32 commented on src/modules/documentExecution/dashboard/widget/ChartWidget/Highcharts/dataProxy/HighchartsPieDataProxy copy.ts
Yeah il look into this, something weird happened, need to change a few files.

2023-06-27 08:54 UTC, dbulatovicx32 commented on src/modules/documentExecution/dashboard/widget/ChartWidget/Highcharts/dataProxy/HighchartsPieDataProxy copy.ts
Fixed

2023-06-27 10:16 UTC, Redjaw approved these changes

2023-06-27 10:16 UTC, merged